# ... (name, on, env, build-and-push-to-ghcr job 保持不变) ...

deploy-to-cvm:
  name: Deploy User Hub to Tencent Cloud CVM
  runs-on: ubuntu-latest
  needs: build-and-push-to-ghcr

  steps:
    - name: Deploy User Hub to CVM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CVM_HOST }}
        username: ${{ secrets.CVM_USERNAME }}
        key: ${{ secrets.CVM_SSH_PRIVATE_KEY }}
        command_timeout: 20m

        script: |
          # ... (前面的脚本保持不变) ...
          
          echo "启动新容器并注入 user_hub 的生产环境变量..."
          docker run -d \
            -p ${HOST_PORT}:${{ env.APP_CONTAINER_PORT }} \
            --name ${CONTAINER_NAME} \
            --network ${DOCKER_NETWORK_NAME} \
            -e SERVERCONFIG_PORT="${{ env.APP_CONTAINER_PORT }}" \
            -e ZAPCONFIG_LEVEL="info" \
            -e GORMLOGCONFIG_LEVEL="warn" \
            -e TRACERCONFIG_ENABLED="false" \
            -e JWTCONFIG_SECRET_KEY="${{ secrets.PROD_JWT_SECRET_KEY }}" \
            -e JWTCONFIG_REFRESH_SECRET="${{ secrets.PROD_JWT_REFRESH_SECRET }}" \
            -e MYSQLCONFIG_DSN="root:root@tcp(mysql-primary:3306)/doer_userHub?charset=utf8mb4&parseTime=true&loc=Local" \
            -e REDISCONFIG_ADDRESS="redis:6379" \
            -e REDISCONFIG_PASSWORD="root" \
            -e WECHATCONFIG_APPID="${{ secrets.PROD_WECHAT_APPID }}" \
            -e WECHATCONFIG_SECRET="${{ secrets.PROD_WECHAT_SECRET }}" \
            -e COSCONFIG_SECRET_ID="${{ secrets.PROD_COS_SECRET_ID }}" \
            -e COSCONFIG_SECRET_KEY="${{ secrets.PROD_COS_SECRET_KEY }}" \
            -e COSCONFIG_BUCKET_NAME="doer-user-hub" \
            -e COSCONFIG_APP_ID="1258994983" \
            -e COSCONFIG_REGION="ap-guangzhou" \
            -e COSCONFIG_BASE_URL="https://doer-user-hub-1258994983.cos.ap-guangzhou.myqcloud.com" \
            -e COOKIECONFIG_SECURE="true" \
            -e COOKIECONFIG_DOMAIN="${{ secrets.PROD_COOKIE_DOMAIN || '' }}" \
            -e COOKIECONFIG_REFRESH_TOKEN_NAME="prod_rt" \
            ${IMAGE_TO_PULL_FULL_NAME}
          
          # ... (后面的脚本保持不变) ...